# Generated by Django 4.2.16 on 2024-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_residents'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('official_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
