# Generated by Django 4.2.16 on 2024-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_requests_residentss_delete_residents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_by', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
