# Generated by Django 4.2.16 on 2024-11-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyHotlines',
            fields=[
                ('hotline_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
